### ISSUE TITLE
Inquiry Regarding Contribution to WebiU 2.0 Project

### ISSUE THREAD

**Issue by UdaySagar-Git** [c2siorg/Webiu#1]
Hey there,

I hope this message finds you well. Firstly, I'd like to extend my apologies for raising an issue here; I understand this might not be the typical channel for such inquiries.

I am Uday, a computer science undergraduate with a passion for full-stack development, including expertise in Next.js, React, TypeScript, JavaScript, Node.js, Tailwind CSS, Electron, Docker, CI/CD, Java, Python, C++, and Angular. I recently came across the WebiU 2.0 project in your organization, particularly interested in its dynamic organization website initiative.

After visiting the GitHub repository , I couldn't find a clear path to the Slack channel mentioned in the project documentation. I attempted to join c2si.slack.com, but unfortunately, it's not accepting email signups.

I'm very much interested in contributing to the WebiU 2.0 project and would appreciate your guidance on the next steps. Could you confirm if this is the correct repository to contribute to? If so, what specific tasks or issues should I focus on first? Additionally, any information on alternative communication channels for the project would be immensely helpful.

About me: I bring a diverse tech stack and a keen interest in contributing meaningfully to open source projects. I am excited about the prospect of working on the dynamic organization website, and I'm committed to making a positive impact on the project.

Thank you for your understanding, and I look forward to your guidance.

Best regards,

Uday

@Maahi10001

**Comment by Maahi10001** [comment]
https://app.slack.com/huddle/T06C3R6HVNG/C06E698JDNY can join here
