### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by sakshamgupta912** [c2siorg/Webiu#100]
**Is your feature request related to a problem? Please describe.**  
I'm always frustrated when using the application for extended periods in low-light environments, as the bright interface causes eye strain and discomfort. Switching between dark-mode-friendly applications and this application is also jarring, making it harder to work smoothly.

**Describe the solution you'd like**  
I would like a dark mode option that adjusts the interface to a darker color scheme. This would make it easier on the eyes during nighttime or in dimly lit settings. Ideally, it would include an option to toggle between light and dark mode manually or automatically based on system settings.

**Describe alternatives you've considered**  
As an alternative, I've tried reducing the screen brightness or using third-party applications that apply a dark overlay to the screen. However, these solutions don’t offer the same ease of reading or the optimized contrast levels that a native dark mode would provide.

**Additional Info:**  
Having a dark mode would not only improve usability but could also help with battery conservation on mobile devices with OLED displays.

**Comment by sakshamgupta912** [comment]
@rajutkarsh07 i would like to work on this

**Comment by rajutkarsh07** [comment]
I am assigning this issue to you but start working on this issue after some days after I will fix some CSS

**Comment by sakshamgupta912** [comment]
Sure

**Comment by sakshamgupta912** [comment]
> I am assigning this issue to you but start working on this issue after some days after I will fix some CSS
@rajutkarsh07 give me a heads up when i can start with this

**Comment by sakshamgupta912** [comment]
@rajutkarsh07 I have added a PR kindly check
