### ISSUE TITLE
Add DarkMode

### ISSUE THREAD

**Issue by Harshsaini001** [c2siorg/Webiu#112]
**Is your feature request related to a problem? Please describe.**

I’m always frustrated when using applications in low-light environments or at night because the bright interface causes eye strain. Additionally, it can be distracting for others nearby and negatively impacts my ability to focus for extended periods. A dark mode option would provide a more comfortable viewing experience, reduce glare, and conserve battery life on devices with OLED screens.
**Describe the solution you'd like**
I would like the application to include a Dark Mode option that switches the interface to a darker color palette, such as dark gray or black backgrounds with light-colored text. This mode should be accessible through the settings menu, with an option to toggle between Light Mode, Dark Mode, and System Default (to follow the device's theme settings). The implementation should ensure good contrast for readability and maintain visual appeal across all app sections.
**Describe alternatives you've considered**
I’ve considered using third-party tools or system-wide dark mode options available on some devices. However, these solutions are inconsistent and often result in poor UI rendering or incomplete implementation within the app. Another alternative is manually adjusting the screen brightness, but this does not solve the issue of eye strain caused by the bright interface itself.

<!--- Note: This template is not strictly to be bound about; if you feel to give additional info, please go ahead.

**Comment by Harshsaini001** [comment]
Please assign @rajutkarsh07 .

**Comment by rajutkarsh07** [comment]
Dark mode is already there
