### ISSUE TITLE
WebiU 2.0 Pre-GSoC Task 
Channel link :-  https://c2si-org.slack.com/archives/C06E698JDNY

### ISSUE THREAD

**Issue by Maahi10001** [c2siorg/Webiu#2]
**Workflow Design:**

- > Define a data flow process to fetch project information from GitHub repositories and integrate it into the organization's website, ensuring real-time updates.
- > Establish mechanisms for automatic website updates triggered by changes in GitHub repositories, utilizing webhooks or periodic checks.
- > Implement error handling protocols to manage exceptions during data retrieval or integration, including logging errors and implementing fallback mechanisms.

**Figma Design for UI:**

- > Create wireframes and UI designs for the organization's website interface, focusing on project display sections, admin control panels, and configuration settings.
- > Develop UI components such as project cards and navigation menus, ensuring a cohesive and user-friendly interface with attention to visual hierarchy and typography.
- > Prototype interactions within the interface using Figma, simulating user actions like toggling project visibility or updating project details.

**Backend Design:**

- > Select a suitable backend technology based on scalability, performance, and integration capabilities with GitHub APIs and also why you are selecting it and some Ideas on Implement RESTful API endpoints for communication between the frontend and backend, enabling actions such as retrieving project information, managing configurations, and updating settings while ensuring security through authentication and authorization mechanisms.

**Note: All These should follow project description and requirements only**

**please keep task result with URL accessible and secure, can mail them to mahender@c2si.org for any queries or suggestions, Reach out to slack channel or write to mahender@c2si.org  All the best and keep coding ;)**

**Comment by Abhiram0304** [comment]
Hello @Maahi10001 !

I'm a second-year CSE undergrad at NIT Andhra Pradesh, India. I have proficient skills in Full-stack Web Development, particularly in the MERN stack, and I use Tailwind CSS and Material UI for highly responsive UI designs. I have experience in developing projects using these technologies.

Additionally, I'm well-versed in database management with MySQL and PostgreSQL, utilizing ORMs like Prisma for efficient data handling. Moreover, I employ Zod validation for robust input validation, ensuring data integrity and security.

I came across the "WebiU 2.0 :- c2siorg/SCoRe Lab website" (#project2) project for GSoC'24 , and I believe I can make valuable contributions to it. Could you please suggest any initial issues or paths where I can start contributing other than application submission?

Thank you!

Email: tanneriabhi@gmail.com
LinkedIn: https://www.linkedin.com/in/abhiram-t-2619a2251/
Here is my best work: https://study-notion-olive.vercel.app/
