### ISSUE TITLE
Having trouble setting up the project locally.

### ISSUE THREAD

**Issue by ShashwatPS** [c2siorg/Webiu#3]
**Describe the bug**
Upon running npm install initially, I encountered an error related to conflicting dependencies. I attempted to resolve it by using npm i --legacy-peer-deps. However, I encountered the following error afterward:
```
stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
npm ERR! gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:419:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:511:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1098:16)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:304:5)
npm ERR! gyp ERR! System Windows_NT 10.0.22631
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\shash\\Desktop\\Webiu\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\shash\Desktop\Webiu\node_modules\sharp
npm ERR! gyp ERR! node -v v20.3.1
npm ERR! gyp ERR! node-gyp -v v3.8.0
``` 
 
**To Reproduce**
1. Navigate to the main directory of Webiu using cd webiu.
2. Execute npm install --legacy-peer-deps.
3. Observe the error message in the terminal.

**Expected behavior**
After running npm install, the application should function correctly when executing npm develop or gatsby develop.

**Screenshots**
![Legacy Peers](https://github.com/c2siorg/Webiu/assets/114943221/3f045aaa-5a86-4778-a5e2-5da1905dbed5)
![npm install](https://github.com/c2siorg/Webiu/assets/114943221/465bb910-ab9d-45fc-b13a-bb069518ba4d)

**Desktop Configurations** 
 - OS: Windows 11
 - IDE: WebStorm 
 - Node Version: 20.3.1

**Comment by 6D-pixel** [comment]
Use Node Version: 14 and try  $ npm install
