### ISSUE TITLE
css changes for responsiveness for all the pages

### ISSUE THREAD

**Issue by rajutkarsh07** [c2siorg/Webiu#33]
**Describe the bug**
Please be detailed about the bug

**To Reproduce**

**Expected behavior**
A detailed description of the expected behaviour

**Screenshots**
If possible, please use screenshots

**Desktop (please complete the following information):**
 - OS: [e.g. iOS/Windows]
 - Browser [e.g. chrome]

**Smartphone (please complete the following information):**
 - Browser [e.g. mozilla, safari]

**Comment by Maahi10001** [comment]
@rajutkarsh07  WHAT IS THE STATUS OF THIS ISSUE??
