### ISSUE TITLE
npm i not working

### ISSUE THREAD

**Issue by sakshamgupta912** [c2siorg/Webiu#79]
**Describe the bug**
Unable to set up my local environment via npm i, getting dependency issues

**To Reproduce**
1. Go to 'https://github.com/c2siorg/Webiu'
2. Clone the repo
3. Go to cli and then to the directory of the project
4. run command npm i
5. See the error of dependency conflicts 

**Expected behaviour**
The packages to get installed properly

**Screenshots**
![image](https://github.com/user-attachments/assets/1bf5efa8-6987-4234-8bfc-ccb8e2984d15)

**Desktop (please complete the following information):**
 - OS: Ubuntu (WSL)
 - Browser: Edge
 -  Version 130.0.2849.46 (Official build) (64-bit)

**Comment by rajutkarsh07** [comment]
move to the feature/webiu-2024 branch and then try to setup it will work
