### ISSUE TITLE
Issue with CI of Frontend

### ISSUE THREAD

**Issue by sakshamgupta912** [c2siorg/Webiu#88]
**Describe the bug**
The frontend deployment pipeline fails during the "Run Angular Tests" step due to an "Unknown argument: sandbox" error. This issue prevents successful deployment and testing of the Angular application.

**To Reproduce**
1. Raise a pull request (PR) with changes in the repository.
2. Go to the GitHub Actions tab to view the running pipeline.
3. Locate the "frontend deployment" pipeline and observe the error during the "Run Angular Tests" stage.

**Expected behavior**
The pipeline should successfully complete all steps, including running Angular tests without encountering any argument errors.

**Screenshots**
![image](https://github.com/user-attachments/assets/b872af9f-c71c-4224-a676-acf641785445)

**Desktop (please complete the following information):**
- OS: Windows 10
- Browser: Chrome
- Version: 116

**Smartphone (please complete the following information):**
- Device: Not applicable for this issue
- OS: Not applicable for this issue
- Browser: Not applicable for this issue
- Version: Not applicable for this issue

**Comment by rajutkarsh07** [comment]
I will fix this later
