### ISSUE TITLE
The alignment of the text "Issues" ,"Pull Requests" and "Contribute" buttons in the project cards is off, causing an inconsistent layout.

### ISSUE THREAD

**Issue by sakshamgupta912** [c2siorg/Webiu#90]
**Describe the bug**
The alignment of the text "Issues", "Pull Requests" and "Contribute" buttons in the project cards is off, causing an inconsistent layout. The buttons are not aligned properly within the card, which makes the UI appear unpolished.

**To Reproduce**

Go to the "Projects" page.
Scroll down to see the list of projects.
Observe the "Issues" , "Pull Requests" and "Contribute" text within the project cards.
Notice the misalignment.

**Expected behavior**
The "Issues", "Pull Requests" and "Contribute" text should be aligned properly within the button of the project card, providing a clean and consistent appearance.

**Screenshots**
![image](https://github.com/user-attachments/assets/1a6e002d-f2dd-488f-8043-280818194fe6)

**Desktop (please complete the following information):**
OS: Windows 10
Browser: Chrome
Version: 116

**Comment by rajutkarsh07** [comment]
there are other changes as well I will create issue about it later
